### ISSUE TITLE
Grafana plugin installation error: permision denied.

### ISSUE THREAD

**Issue by dspdavinci** [guessi/docker-compose-grafana-influxdb#1]
**After running docker-compose up:**
...
grafana_1   | installing grafana-clock-panel @ 0.1.0
grafana_1   | from url: https://grafana.com/api/plugins/grafana-clock-panel/versions/0.1.0/download
grafana_1   | into: /var/lib/grafana/plugins
grafana_1   | 
grafana_1   | 
grafana_1   | Error: ✗ Could not create /var/lib/grafana/plugins/grafana-clock-panel. Permission denied. Make sure you have write access to plugindir
grafana_1   | 
grafana_1   | NAME:
grafana_1   |    Grafana cli plugins install - install <plugin id> <plugin version (optional)>
grafana_1   | 
grafana_1   | USAGE:
grafana_1   |    Grafana cli plugins install [arguments...]
demo_grafana_1 exited with code 1

**Comment by guessi** [comment]
@dspdavinci thanks for your report, and it's now fixed. :sunglasses: 

please pull the latest commit and try again.
