### ISSUE TITLE
just a question ?

### ISSUE THREAD

**Issue by rizerzero** [guessi/docker-compose-grafana-influxdb#2]
What is so dangerous about using these tools in production?

**Comment by guessi** [comment]
@rizerzero Umm... it could be use for production for sure, I would change the wording later.

What I trying to say is that DO NOT use in PRODUCTION without changing env files.

- https://github.com/guessi/docker-compose-grafana-influxdb/blob/master/demo.env

**Comment by rizerzero** [comment]
@guessi  Thank you so much for your answer Sir, English is not my native language too ^^ so I totally understand. 
To me these technologies are stable and you did a great job ! so there was no problem for me as I'm using these tools for production.

Have a nice day sir.

**Comment by guessi** [comment]
@rizerzero Thanks for report.
I've update the wording to avoid misunderstanding. Please check current master branch for the changes.
