### ISSUE TITLE
grafana.ini not mounted in docker-composer.yml

### ISSUE THREAD

**Issue by suhasrkms** [guessi/docker-compose-grafana-influxdb#7]
Making changes in grafana.ini is not reflection since its not been mounted. @guessi

**Comment by guessi** [comment]
@suhasrkms Could you please confirm how you update the ini file?

I think it should be mount via volume where you may find the mount config [HERE](https://github.com/guessi/docker-compose-grafana-influxdb/blob/master/docker-compose.yaml#L21-L21).

**Comment by suhasrkms** [comment]
To ensure that the ini file is recognized, we must mount the docker-composer file. I have shared a pull request containing the updated code. Please feel free to review it and proceed. @guessi
